version: 2
jobs:
    build:
        branches:
            only:
              - master
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
        steps:
            - checkout
            - run:
                name: Restore Packages
                command: dotnet restore
            - run:
                name: Run our tests
                command: dotnet test
            - run:
                name: Build
                command: dotnet build -c Release
